name: call_manager
description: Call Manager in Flutter
version: 2.8.5+54
publish_to: none

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  bluejay: ^2.0.0
  cloud_firestore: ^5.4.5
  # contacts_service: ^0.6.3
  contacts_service:
    git:
      url: https://github.com/GroovinChip/flutter_contacts.git
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  datetime_picker_formfield: ^2.0.1
  direct_dialer: ^2.0.1
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  flutter_local_notifications: ^18.0.1
  flutter_typeahead: ^5.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  groovin_widgets: ^3.2.0
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^8.1.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.3.3
  sign_in_with_apple: ^6.1.3
  timezone: any
  url_launcher: ^6.3.1
  wiredash: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: "^0.7.2"
#  dart_code_metrics: ^5.7.6
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  #image_path: "assets/icon/call_manager_app_icon.png"
  #adaptive_icon_background: "#1976D2"

flutter:
  uses-material-design: true

  assets:
    - android/app/src/main/res/drawable-hdpi/ic_notification.png
    - assets/icon/call_manager_app_icon.png
    - assets/glogo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 500
