// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs2Vch4b2plINC3gqZ3Ksf1GAtquIlvnA',
    appId: '1:1053316160376:android:9e3c10e86de5057f',
    messagingSenderId: '1053316160376',
    projectId: 'call-manager-flutter-db',
    databaseURL: 'https://call-manager-flutter-db.firebaseio.com',
    storageBucket: 'call-manager-flutter-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHw5ZUSRFFr506s5tDwjRBXNVauqsZ854',
    appId: '1:1053316160376:ios:3f44ce63a1c0a5fba4868d',
    messagingSenderId: '1053316160376',
    projectId: 'call-manager-flutter-db',
    databaseURL: 'https://call-manager-flutter-db.firebaseio.com',
    storageBucket: 'call-manager-flutter-db.firebasestorage.app',
    androidClientId: '1053316160376-5juugktuaas98do08thao9iplqmr5fn9.apps.googleusercontent.com',
    iosClientId: '1053316160376-117rp70a5ps0s6nk98th54trgsacoaim.apps.googleusercontent.com',
    iosBundleId: 'dev.groovinchip.callmanager',
  );
}
